apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-vj2rnapjdpttl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-vj2rnapjdpttl
    app.kubernetes.io/part-of: test-gitlabrenovate-d3qq8zv7ubv1b
  name: component-vj2rnapjdpttl
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-vj2rnapjdpttl
status:
  loadBalancer: {}
